version: '3.8'

services:
  # Ollama LLM Service
  ollama:
    image: ollama/ollama:latest
    container_name: llm-location-ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - llm-network

  # Main Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: llm-location-app
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
      - LLM_BASE_URL=http://ollama:11434/v1
      - LLM_MODEL=${LLM_MODEL:-llama3}
      - APP_HOST=0.0.0.0
      - APP_PORT=8000
      - DEBUG=${DEBUG:-False}
    depends_on:
      - ollama
    restart: unless-stopped
    networks:
      - llm-network
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/api/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  llm-network:
    driver: bridge

volumes:
  ollama_data:
    driver: local
